'use client'

import Link from 'next/link'
import { ClockIcon, ArrowTopRightOnSquareIcon, RssIcon } from '@heroicons/react/24/outline'

interface Article {
  id: string
  title: string
  summary: string
  url: string
  publishedAt: string
  source: {
    name: string
    favicon: string
  }
  readTime: number
}

interface DigestData {
  date: string
  articles: Article[]
  totalArticles: number
  readTime: number
}

interface DigestPreviewProps {
  digestData: DigestData
}

export function DigestPreview({ digestData }: DigestPreviewProps) {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  }

  const formatTime = (dateString: string) => {
    return new Date(dateString).toLocaleTimeString('en-US', {
      hour: 'numeric',
      minute: '2-digit'
    })
  }

  return (
    <div className="max-w-2xl mx-auto p-8">
      {/* Header */}
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-50 text-indigo-700 rounded-full text-sm font-medium mb-4">
          <div className="w-5 h-5 bg-gradient-to-br from-indigo-600 to-violet-600 rounded-md flex items-center justify-center">
            <RssIcon className="w-3 h-3 text-white" />
          </div>
          Daily Digest
        </div>

        <h1 className="text-2xl font-bold text-gray-900 mb-2">
          Your News Summary
        </h1>
        <p className="text-gray-500 text-sm">
          {formatDate(digestData.date)} &middot; {digestData.totalArticles} articles &middot; {digestData.readTime} min read
        </p>
      </div>

      {/* Summary Stats */}
      <div className="bg-gradient-to-br from-indigo-50 to-violet-50 rounded-2xl p-5 mb-8 text-center border border-indigo-100">
        <div className="text-3xl font-bold text-gray-900 mb-1">{digestData.totalArticles}</div>
        <div className="text-sm text-gray-500">articles summarized from your subscriptions</div>
      </div>

      {/* Articles */}
      <div className="space-y-8">
        {digestData.articles.map((article, index) => (
          <article key={article.id} className="border-b border-gray-100 pb-8 last:border-b-0 last:pb-0">
            <div className="flex items-center gap-3 mb-3">
              <div className="w-7 h-7 bg-gradient-to-br from-indigo-600 to-violet-600 text-white rounded-lg flex items-center justify-center text-xs font-bold shadow-sm">
                {index + 1}
              </div>
              <div className="flex items-center gap-2 text-xs text-gray-500">
                <img src={article.source.favicon} alt="" className="w-4 h-4 rounded" />
                <span className="font-medium">{article.source.name}</span>
                <span>&middot;</span>
                <span>{formatTime(article.publishedAt)}</span>
                <span>&middot;</span>
                <div className="flex items-center gap-1">
                  <ClockIcon className="w-3 h-3" />
                  <span>{article.readTime} min</span>
                </div>
              </div>
            </div>

            <h2 className="text-lg font-semibold text-gray-900 mb-3 leading-snug">{article.title}</h2>
            <div className="text-gray-600 mb-4 leading-relaxed text-sm">{article.summary}</div>

            <a href={article.url} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center text-indigo-600 hover:text-indigo-700 text-sm font-medium">
              Read full article
              <ArrowTopRightOnSquareIcon className="w-3 h-3 ml-1" />
            </a>
          </article>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-12 pt-8 border-t border-gray-200 text-center">
        <div className="text-sm text-gray-500 mb-4">This digest was generated by AI based on your feed subscriptions.</div>
        <div className="flex items-center justify-center gap-4 text-xs text-gray-400">
          <Link href="/preferences" className="hover:text-indigo-600 transition-colors">Manage Preferences</Link>
          <span>&middot;</span>
          <Link href="/feeds" className="hover:text-indigo-600 transition-colors">View All Feeds</Link>
          <span>&middot;</span>
          <Link href="/preferences" className="hover:text-indigo-600 transition-colors">Unsubscribe</Link>
        </div>
        <div className="text-xs text-gray-400 mt-4">&copy; 2026 Briefly. All rights reserved.</div>
      </div>
    </div>
  )
}
