'use client'

interface Article {
  id: string
  title: string
  summary: string
  url: string
  publishedAt: string
  source: {
    name: string
    favicon: string
  }
  readTime: number
}

interface DigestData {
  date: string
  articles: Article[]
  totalArticles: number
  readTime: number
}

interface EmailTemplateProps {
  digestData: DigestData
}

export function EmailTemplate({ digestData }: EmailTemplateProps) {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
    })
  }

  const formatTime = (dateString: string) => {
    return new Date(dateString).toLocaleTimeString('en-US', {
      hour: 'numeric', minute: '2-digit'
    })
  }

  return (
    <div className="bg-gray-100 p-8">
      <div className="max-w-2xl mx-auto">
        <div className="bg-white rounded-xl shadow-sm overflow-hidden"
          style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', fontSize: '16px', lineHeight: '1.6', color: '#333' }}>
          {/* Header */}
          <div style={{ background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)', padding: '32px 24px', textAlign: 'center' as const }}>
            <div style={{ color: 'white', fontSize: '24px', fontWeight: 'bold', marginBottom: '8px' }}>Briefly</div>
            <div style={{ color: '#c7d2fe', fontSize: '14px' }}>Your Daily News Digest</div>
          </div>

          {/* Body */}
          <div style={{ padding: '32px 24px' }}>
            <div style={{ marginBottom: '32px', textAlign: 'center' as const }}>
              <h1 style={{ fontSize: '24px', fontWeight: 'bold', color: '#1f2937', margin: '0 0 12px 0' }}>Your News Summary</h1>
              <p style={{ color: '#6b7280', fontSize: '14px', margin: '0' }}>
                {formatDate(digestData.date)} &middot; {digestData.totalArticles} articles &middot; {digestData.readTime} min read
              </p>
            </div>

            <div style={{ background: 'linear-gradient(135deg, #eef2ff 0%, #f5f3ff 100%)', border: '1px solid #e0e7ff', borderRadius: '12px', padding: '24px', textAlign: 'center' as const, marginBottom: '32px' }}>
              <div style={{ fontSize: '32px', fontWeight: 'bold', color: '#1f2937', marginBottom: '4px' }}>{digestData.totalArticles}</div>
              <div style={{ fontSize: '14px', color: '#6b7280' }}>articles summarized from your subscriptions</div>
            </div>

            {digestData.articles.map((article, index) => (
              <div key={article.id} style={{
                borderBottom: index < digestData.articles.length - 1 ? '1px solid #f3f4f6' : 'none',
                paddingBottom: '28px', marginBottom: index < digestData.articles.length - 1 ? '28px' : '0'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', marginBottom: '12px', fontSize: '13px', color: '#6b7280' }}>
                  <div style={{ background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)', color: 'white', borderRadius: '8px', width: '26px', height: '26px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '12px', fontWeight: 'bold', marginRight: '12px', flexShrink: 0 }}>{index + 1}</div>
                  <span style={{ fontWeight: 500 }}>{article.source.name}</span>
                  <span style={{ margin: '0 6px' }}>&middot;</span>
                  <span>{formatTime(article.publishedAt)}</span>
                  <span style={{ margin: '0 6px' }}>&middot;</span>
                  <span>{article.readTime} min read</span>
                </div>
                <h2 style={{ fontSize: '18px', fontWeight: '600', color: '#1f2937', margin: '0 0 12px 0', lineHeight: '1.4' }}>{article.title}</h2>
                <div style={{ color: '#4b5563', fontSize: '15px', lineHeight: '1.6', marginBottom: '14px' }}>{article.summary}</div>
                <a href={article.url} style={{ color: '#4f46e5', textDecoration: 'none', fontSize: '14px', fontWeight: '500' }}>Read full article &rarr;</a>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div style={{ backgroundColor: '#f9fafb', borderTop: '1px solid #f3f4f6', padding: '24px', textAlign: 'center' as const }}>
            <div style={{ fontSize: '13px', color: '#6b7280', marginBottom: '16px' }}>This digest was generated by AI based on your feed subscriptions.</div>
            <div style={{ fontSize: '12px', color: '#9ca3af', marginBottom: '16px' }}>
              <a href="/preferences" style={{ color: '#6366f1', textDecoration: 'none', marginRight: '16px' }}>Manage Preferences</a>
              <a href="/feeds" style={{ color: '#6366f1', textDecoration: 'none', marginRight: '16px' }}>View All Feeds</a>
              <a href="/preferences" style={{ color: '#6366f1', textDecoration: 'none' }}>Unsubscribe</a>
            </div>
            <div style={{ fontSize: '12px', color: '#9ca3af' }}>&copy; 2026 Briefly. All rights reserved.</div>
          </div>
        </div>

        <div style={{ marginTop: '20px', padding: '14px 16px', backgroundColor: '#fef3c7', border: '1px solid #fbbf24', borderRadius: '12px', fontSize: '12px', color: '#92400e' }}>
          <strong>Preview note:</strong> This is a preview of how your email will appear. Actual appearance may vary by email client.
        </div>
      </div>
    </div>
  )
}
